/*
 * Système de Gestion de Tickets (SBIR), API REST
 * API REST pour le système de gestion de tickets développé en Java pour le cours 6GEI311, Architecture Logicielle  Auteurs: Il'aina Ratefinanahary et Samuel Brassard, UQAC Automne 2025 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: iratefinan@etu.uqac.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.CommentRequest;
import org.openapitools.client.model.ErrorResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CommentsApi
 */
@Disabled
public class CommentsApiTest {

    private final CommentsApi api = new CommentsApi();

    /**
     * Ajoute un commentaire à un ticket
     *
     * Ajoute un nouveau commentaire à un ticket. Admins et développeurs peuvent commenter tous les tickets. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void addCommentTest() throws ApiException {
        Integer ticketId = null;
        CommentRequest commentRequest = null;
        String response = api.addComment(ticketId, commentRequest);
        // TODO: test validations
    }

    /**
     * Supprime tous les commentaires d&#39;un ticket
     *
     * Efface tous les commentaires associés à un ticket
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void clearCommentsTest() throws ApiException {
        Integer ticketId = null;
        api.clearComments(ticketId);
        // TODO: test validations
    }

    /**
     * Liste les commentaires d&#39;un ticket
     *
     * Retourne tous les commentaires associés à un ticket
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getTicketCommentsTest() throws ApiException {
        Integer ticketId = null;
        List<String> response = api.getTicketComments(ticketId);
        // TODO: test validations
    }

}
