/*
 * Système de Gestion de Tickets (SBIR), API REST
 * API REST pour le système de gestion de tickets développé en Java pour le cours 6GEI311, Architecture Logicielle  Auteurs: Il'aina Ratefinanahary et Samuel Brassard, UQAC Automne 2025 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: iratefinan@etu.uqac.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.ErrorResponse;
import java.io.File;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ExportApi
 */
@Disabled
public class ExportApiTest {

    private final ExportApi api = new ExportApi();

    /**
     * Exporte un ticket en PDF
     *
     * Génère et exporte le contenu d&#39;un ticket en format PDF. Utilise le pattern Strategy (PDFExporter) côté serveur. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void exportTicketToPDFTest() throws ApiException {
        Integer ticketId = null;
        Integer userId = null;
        File response = api.exportTicketToPDF(ticketId, userId);
        // TODO: test validations
    }

}
