/*
 * Système de Gestion de Tickets (SBIR), API REST
 * API REST pour le système de gestion de tickets développé en Java pour le cours 6GEI311, Architecture Logicielle  Auteurs: Il'aina Ratefinanahary et Samuel Brassard, UQAC Automne 2025 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: iratefinan@etu.uqac.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.AddImageRequest;
import org.openapitools.client.model.AddVideoRequest;
import org.openapitools.client.model.ErrorResponse;
import org.openapitools.client.model.GetTicketImages200Response;
import org.openapitools.client.model.TicketDTO;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for MediaApi
 */
@Disabled
public class MediaApiTest {

    private final MediaApi api = new MediaApi();

    /**
     * Ajoute une image à la description du ticket
     *
     * Ajoute un chemin d&#39;image à la description d&#39;un ticket spécifique
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void addImageToTicketTest() throws ApiException {
        Integer ticketId = null;
        AddImageRequest addImageRequest = null;
        TicketDTO response = api.addImageToTicket(ticketId, addImageRequest);
        // TODO: test validations
    }

    /**
     * Ajoute une vidéo à la description du ticket
     *
     * Ajoute un chemin de vidéo à la description d&#39;un ticket spécifique
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void addVideoToTicketTest() throws ApiException {
        Integer ticketId = null;
        AddVideoRequest addVideoRequest = null;
        TicketDTO response = api.addVideoToTicket(ticketId, addVideoRequest);
        // TODO: test validations
    }

    /**
     * Récupère les images d&#39;un ticket
     *
     * Retourne la liste de tous les chemins d&#39;images associés à la description du ticket
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getTicketImagesTest() throws ApiException {
        Integer ticketId = null;
        GetTicketImages200Response response = api.getTicketImages(ticketId);
        // TODO: test validations
    }

}
