/*
 * Système de Gestion de Tickets (SBIR), API REST
 * API REST pour le système de gestion de tickets développé en Java pour le cours 6GEI311, Architecture Logicielle  Auteurs: Il'aina Ratefinanahary et Samuel Brassard, UQAC Automne 2025 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: iratefinan@etu.uqac.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.ErrorResponse;
import org.openapitools.client.model.TicketDTO;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SearchApi
 */
@Disabled
public class SearchApiTest {

    private final SearchApi api = new SearchApi();

    /**
     * Récupère les tickets critiques
     *
     * Retourne tous les tickets avec priorité CRITIQUE
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getCriticalTicketsTest() throws ApiException {
        List<TicketDTO> response = api.getCriticalTickets();
        // TODO: test validations
    }

    /**
     * Récupère les tickets par priorité
     *
     * Retourne tous les tickets ayant une priorité spécifique
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getTicketsByPriorityTest() throws ApiException {
        String priority = null;
        List<TicketDTO> response = api.getTicketsByPriority(priority);
        // TODO: test validations
    }

    /**
     * Récupère les tickets par statut
     *
     * Retourne tous les tickets ayant un statut spécifique
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getTicketsByStatusTest() throws ApiException {
        String status = null;
        List<TicketDTO> response = api.getTicketsByStatus(status);
        // TODO: test validations
    }

    /**
     * Récupère les tickets d&#39;un utilisateur
     *
     * Retourne tous les tickets assignés à un utilisateur spécifique
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getTicketsByUserTest() throws ApiException {
        Integer userId = null;
        List<TicketDTO> response = api.getTicketsByUser(userId);
        // TODO: test validations
    }

    /**
     * Récupère les tickets non assignés
     *
     * Retourne tous les tickets ouverts qui ne sont pas encore assignés
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getUnassignedTicketsTest() throws ApiException {
        List<TicketDTO> response = api.getUnassignedTickets();
        // TODO: test validations
    }

    /**
     * Recherche des tickets par titre
     *
     * Recherche des tickets dont le titre contient la chaîne spécifiée
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void searchTicketsByTitleTest() throws ApiException {
        String title = null;
        List<TicketDTO> response = api.searchTicketsByTitle(title);
        // TODO: test validations
    }

}
