/*
 * Système de Gestion de Tickets (SBIR), API REST
 * API REST pour le système de gestion de tickets développé en Java pour le cours 6GEI311, Architecture Logicielle  Auteurs: Il'aina Ratefinanahary et Samuel Brassard, UQAC Automne 2025 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: iratefinan@etu.uqac.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.ErrorResponse;
import org.openapitools.client.model.StatusUpdateDTO;
import org.openapitools.client.model.TicketDTO;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for StatusApi
 */
@Disabled
public class StatusApiTest {

    private final StatusApi api = new StatusApi();

    /**
     * Obtenir les transitions disponibles
     *
     * Retourne la liste des statuts vers lesquels une transition est possible
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAvailableTransitionsTest() throws ApiException {
        Integer ticketId = null;
        List<String> response = api.getAvailableTransitions(ticketId);
        // TODO: test validations
    }

    /**
     * Modifie le statut d&#39;un ticket
     *
     * Met à jour le statut d&#39;un ticket spécifique avec validation des transitions.  Transitions autorisées : - OUVERT → ASSIGNE, FERME - ASSIGNE → TERMINE, FERME - TERMINE/FERME → (états finaux, aucune transition)  Seuls les admins et développeurs peuvent changer les statuts. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateTicketStatusTest() throws ApiException {
        Integer ticketId = null;
        StatusUpdateDTO statusUpdateDTO = null;
        TicketDTO response = api.updateTicketStatus(ticketId, statusUpdateDTO);
        // TODO: test validations
    }

}
