/*
 * Système de Gestion de Tickets (SBIR), API REST
 * API REST pour le système de gestion de tickets développé en Java pour le cours 6GEI311, Architecture Logicielle  Auteurs: Il'aina Ratefinanahary et Samuel Brassard, UQAC Automne 2025 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: iratefinan@etu.uqac.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.AssignmentDTO;
import org.openapitools.client.model.CloseTicketRequest;
import org.openapitools.client.model.CreateTicketRequest;
import org.openapitools.client.model.Description;
import org.openapitools.client.model.ErrorResponse;
import org.openapitools.client.model.TicketDTO;
import org.openapitools.client.model.UnassignTicketRequest;
import org.openapitools.client.model.UpdateTicketPriorityRequest;
import org.openapitools.client.model.UpdateTicketRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TicketsApi
 */
@Disabled
public class TicketsApiTest {

    private final TicketsApi api = new TicketsApi();

    /**
     * Assigne un ticket à un utilisateur
     *
     * Assigne un ticket à un utilisateur spécifique. Change automatiquement le statut du ticket à ASSIGNE. Seuls les admins peuvent assigner des tickets. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void assignTicketTest() throws ApiException {
        Integer ticketId = null;
        AssignmentDTO assignmentDTO = null;
        TicketDTO response = api.assignTicket(ticketId, assignmentDTO);
        // TODO: test validations
    }

    /**
     * Ferme/termine un ticket
     *
     * Marque un ticket comme terminé
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void closeTicketTest() throws ApiException {
        Integer ticketId = null;
        CloseTicketRequest closeTicketRequest = null;
        TicketDTO response = api.closeTicket(ticketId, closeTicketRequest);
        // TODO: test validations
    }

    /**
     * Crée un nouveau ticket
     *
     * Crée un nouveau ticket dans le système
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createTicketTest() throws ApiException {
        CreateTicketRequest createTicketRequest = null;
        TicketDTO response = api.createTicket(createTicketRequest);
        // TODO: test validations
    }

    /**
     * Supprime un ticket
     *
     * Supprime un ticket. Seuls les administrateurs peuvent supprimer des tickets. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteTicketTest() throws ApiException {
        Integer ticketId = null;
        api.deleteTicket(ticketId);
        // TODO: test validations
    }

    /**
     * Liste tous les tickets
     *
     * Retourne la liste de tous les tickets du système avec filtrage optionnel
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAllTicketsTest() throws ApiException {
        String status = null;
        Integer assignedTo = null;
        String priority = null;
        List<TicketDTO> response = api.getAllTickets(status, assignedTo, priority);
        // TODO: test validations
    }

    /**
     * Récupère un ticket spécifique
     *
     * Retourne les informations complètes d&#39;un ticket spécifique
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getTicketByIdTest() throws ApiException {
        Integer ticketId = null;
        TicketDTO response = api.getTicketById(ticketId);
        // TODO: test validations
    }

    /**
     * Désassigne un ticket
     *
     * Retire l&#39;assignation d&#39;un ticket
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void unassignTicketTest() throws ApiException {
        Integer ticketId = null;
        UnassignTicketRequest unassignTicketRequest = null;
        TicketDTO response = api.unassignTicket(ticketId, unassignTicketRequest);
        // TODO: test validations
    }

    /**
     * Met à jour un ticket
     *
     * Modifie un ticket existant. Les admins/développeurs peuvent modifier tous les tickets. Les utilisateurs ne peuvent modifier que leurs propres tickets. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateTicketTest() throws ApiException {
        Integer ticketId = null;
        UpdateTicketRequest updateTicketRequest = null;
        TicketDTO response = api.updateTicket(ticketId, updateTicketRequest);
        // TODO: test validations
    }

    /**
     * Met à jour la description d&#39;un ticket
     *
     * Modifie la description d&#39;un ticket existant
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateTicketDescriptionTest() throws ApiException {
        Integer ticketId = null;
        Description description = null;
        TicketDTO response = api.updateTicketDescription(ticketId, description);
        // TODO: test validations
    }

    /**
     * Modifie la priorité d&#39;un ticket
     *
     * Met à jour la priorité d&#39;un ticket spécifique
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateTicketPriorityTest() throws ApiException {
        Integer ticketId = null;
        UpdateTicketPriorityRequest updateTicketPriorityRequest = null;
        TicketDTO response = api.updateTicketPriority(ticketId, updateTicketPriorityRequest);
        // TODO: test validations
    }

}
