/*
 * Système de Gestion de Tickets (SBIR), API REST
 * API REST pour le système de gestion de tickets développé en Java pour le cours 6GEI311, Architecture Logicielle  Auteurs: Il'aina Ratefinanahary et Samuel Brassard, UQAC Automne 2025 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: iratefinan@etu.uqac.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.ErrorResponse;
import org.openapitools.client.model.UserCreate;
import org.openapitools.client.model.UserDTO;
import org.openapitools.client.model.UserUpdate;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UsersApi
 */
@Disabled
public class UsersApiTest {

    private final UsersApi api = new UsersApi();

    /**
     * Crée un nouvel utilisateur
     *
     * Crée un nouvel utilisateur dans le système
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createUserTest() throws ApiException {
        UserCreate userCreate = null;
        UserDTO response = api.createUser(userCreate);
        // TODO: test validations
    }

    /**
     * Supprime un utilisateur
     *
     * Supprime un utilisateur du système
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteUserTest() throws ApiException {
        Integer userId = null;
        api.deleteUser(userId);
        // TODO: test validations
    }

    /**
     * Liste tous les utilisateurs
     *
     * Retourne la liste complète des utilisateurs du système
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAllUsersTest() throws ApiException {
        List<UserDTO> response = api.getAllUsers();
        // TODO: test validations
    }

    /**
     * Récupère un utilisateur spécifique
     *
     * Retourne les détails d&#39;un utilisateur par son ID
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getUserByIdTest() throws ApiException {
        Integer userId = null;
        UserDTO response = api.getUserById(userId);
        // TODO: test validations
    }

    /**
     * Met à jour un utilisateur
     *
     * Met à jour les informations d&#39;un utilisateur existant
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateUserTest() throws ApiException {
        Integer userId = null;
        UserUpdate userUpdate = null;
        UserDTO response = api.updateUser(userId, userUpdate);
        // TODO: test validations
    }

}
