/*
 * Système de Gestion de Tickets (SBIR), API REST
 * API REST pour le système de gestion de tickets développé en Java pour le cours 6GEI311, Architecture Logicielle  Auteurs: Il'aina Ratefinanahary et Samuel Brassard, UQAC Automne 2025 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: iratefinan@etu.uqac.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Description multimédia d&#39;un ticket utilisant le pattern Composite. Supporte le texte, les images et les vidéos. 
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-18T07:17:48.683432600-05:00[America/Toronto]", comments = "Generator version: 7.10.0")
public class Description {
  public static final String SERIALIZED_NAME_TEXT_CONTENT = "textContent";
  @SerializedName(SERIALIZED_NAME_TEXT_CONTENT)
  @javax.annotation.Nullable
  private String textContent;

  public static final String SERIALIZED_NAME_IMAGE_PATHS = "imagePaths";
  @SerializedName(SERIALIZED_NAME_IMAGE_PATHS)
  @javax.annotation.Nullable
  private List<String> imagePaths = new ArrayList<>();

  public static final String SERIALIZED_NAME_VIDEO_PATHS = "videoPaths";
  @SerializedName(SERIALIZED_NAME_VIDEO_PATHS)
  @javax.annotation.Nullable
  private List<String> videoPaths = new ArrayList<>();

  public Description() {
  }

  public Description textContent(@javax.annotation.Nullable String textContent) {
    this.textContent = textContent;
    return this;
  }

  /**
   * Contenu textuel de la description
   * @return textContent
   */
  @javax.annotation.Nullable
  public String getTextContent() {
    return textContent;
  }

  public void setTextContent(@javax.annotation.Nullable String textContent) {
    this.textContent = textContent;
  }


  public Description imagePaths(@javax.annotation.Nullable List<String> imagePaths) {
    this.imagePaths = imagePaths;
    return this;
  }

  public Description addImagePathsItem(String imagePathsItem) {
    if (this.imagePaths == null) {
      this.imagePaths = new ArrayList<>();
    }
    this.imagePaths.add(imagePathsItem);
    return this;
  }

  /**
   * Chemins vers les images attachées
   * @return imagePaths
   */
  @javax.annotation.Nullable
  public List<String> getImagePaths() {
    return imagePaths;
  }

  public void setImagePaths(@javax.annotation.Nullable List<String> imagePaths) {
    this.imagePaths = imagePaths;
  }


  public Description videoPaths(@javax.annotation.Nullable List<String> videoPaths) {
    this.videoPaths = videoPaths;
    return this;
  }

  public Description addVideoPathsItem(String videoPathsItem) {
    if (this.videoPaths == null) {
      this.videoPaths = new ArrayList<>();
    }
    this.videoPaths.add(videoPathsItem);
    return this;
  }

  /**
   * Chemins vers les vidéos attachées
   * @return videoPaths
   */
  @javax.annotation.Nullable
  public List<String> getVideoPaths() {
    return videoPaths;
  }

  public void setVideoPaths(@javax.annotation.Nullable List<String> videoPaths) {
    this.videoPaths = videoPaths;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Description description = (Description) o;
    return Objects.equals(this.textContent, description.textContent) &&
        Objects.equals(this.imagePaths, description.imagePaths) &&
        Objects.equals(this.videoPaths, description.videoPaths);
  }

  @Override
  public int hashCode() {
    return Objects.hash(textContent, imagePaths, videoPaths);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Description {\n");
    sb.append("    textContent: ").append(toIndentedString(textContent)).append("\n");
    sb.append("    imagePaths: ").append(toIndentedString(imagePaths)).append("\n");
    sb.append("    videoPaths: ").append(toIndentedString(videoPaths)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("textContent");
    openapiFields.add("imagePaths");
    openapiFields.add("videoPaths");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Description
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Description.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in Description is not found in the empty JSON string", Description.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Description.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `Description` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("textContent") != null && !jsonObj.get("textContent").isJsonNull()) && !jsonObj.get("textContent").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `textContent` to be a primitive type in the JSON string but got `%s`", jsonObj.get("textContent").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("imagePaths") != null && !jsonObj.get("imagePaths").isJsonNull() && !jsonObj.get("imagePaths").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `imagePaths` to be an array in the JSON string but got `%s`", jsonObj.get("imagePaths").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("videoPaths") != null && !jsonObj.get("videoPaths").isJsonNull() && !jsonObj.get("videoPaths").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `videoPaths` to be an array in the JSON string but got `%s`", jsonObj.get("videoPaths").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Description.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Description' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Description> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Description.class));

       return (TypeAdapter<T>) new TypeAdapter<Description>() {
           @Override
           public void write(JsonWriter out, Description value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Description read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Description given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Description
   * @throws IOException if the JSON string is invalid with respect to Description
   */
  public static Description fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Description.class);
  }

  /**
   * Convert an instance of Description to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

