/*
 * Système de Gestion de Tickets (SBIR), API REST
 * API REST pour le système de gestion de tickets développé en Java pour le cours 6GEI311, Architecture Logicielle  Auteurs: Il'aina Ratefinanahary et Samuel Brassard, UQAC Automne 2025 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: iratefinan@etu.uqac.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * GetTicketImages200Response
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-18T07:17:48.683432600-05:00[America/Toronto]", comments = "Generator version: 7.10.0")
public class GetTicketImages200Response {
  public static final String SERIALIZED_NAME_TICKET_ID = "ticketId";
  @SerializedName(SERIALIZED_NAME_TICKET_ID)
  @javax.annotation.Nullable
  private Integer ticketId;

  public static final String SERIALIZED_NAME_IMAGE_PATHS = "imagePaths";
  @SerializedName(SERIALIZED_NAME_IMAGE_PATHS)
  @javax.annotation.Nullable
  private List<String> imagePaths = new ArrayList<>();

  public GetTicketImages200Response() {
  }

  public GetTicketImages200Response ticketId(@javax.annotation.Nullable Integer ticketId) {
    this.ticketId = ticketId;
    return this;
  }

  /**
   * Get ticketId
   * @return ticketId
   */
  @javax.annotation.Nullable
  public Integer getTicketId() {
    return ticketId;
  }

  public void setTicketId(@javax.annotation.Nullable Integer ticketId) {
    this.ticketId = ticketId;
  }


  public GetTicketImages200Response imagePaths(@javax.annotation.Nullable List<String> imagePaths) {
    this.imagePaths = imagePaths;
    return this;
  }

  public GetTicketImages200Response addImagePathsItem(String imagePathsItem) {
    if (this.imagePaths == null) {
      this.imagePaths = new ArrayList<>();
    }
    this.imagePaths.add(imagePathsItem);
    return this;
  }

  /**
   * Liste des chemins d&#39;images
   * @return imagePaths
   */
  @javax.annotation.Nullable
  public List<String> getImagePaths() {
    return imagePaths;
  }

  public void setImagePaths(@javax.annotation.Nullable List<String> imagePaths) {
    this.imagePaths = imagePaths;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetTicketImages200Response getTicketImages200Response = (GetTicketImages200Response) o;
    return Objects.equals(this.ticketId, getTicketImages200Response.ticketId) &&
        Objects.equals(this.imagePaths, getTicketImages200Response.imagePaths);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ticketId, imagePaths);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetTicketImages200Response {\n");
    sb.append("    ticketId: ").append(toIndentedString(ticketId)).append("\n");
    sb.append("    imagePaths: ").append(toIndentedString(imagePaths)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("ticketId");
    openapiFields.add("imagePaths");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to GetTicketImages200Response
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GetTicketImages200Response.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in GetTicketImages200Response is not found in the empty JSON string", GetTicketImages200Response.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!GetTicketImages200Response.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `GetTicketImages200Response` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the optional json data is an array if present
      if (jsonObj.get("imagePaths") != null && !jsonObj.get("imagePaths").isJsonNull() && !jsonObj.get("imagePaths").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `imagePaths` to be an array in the JSON string but got `%s`", jsonObj.get("imagePaths").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GetTicketImages200Response.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GetTicketImages200Response' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GetTicketImages200Response> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GetTicketImages200Response.class));

       return (TypeAdapter<T>) new TypeAdapter<GetTicketImages200Response>() {
           @Override
           public void write(JsonWriter out, GetTicketImages200Response value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GetTicketImages200Response read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of GetTicketImages200Response given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GetTicketImages200Response
   * @throws IOException if the JSON string is invalid with respect to GetTicketImages200Response
   */
  public static GetTicketImages200Response fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GetTicketImages200Response.class);
  }

  /**
   * Convert an instance of GetTicketImages200Response to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

