/*
 * Système de Gestion de Tickets (SBIR), API REST
 * API REST pour le système de gestion de tickets développé en Java pour le cours 6GEI311, Architecture Logicielle  Auteurs: Il'aina Ratefinanahary et Samuel Brassard, UQAC Automne 2025 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: iratefinan@etu.uqac.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.Description;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Représentation complète d&#39;un ticket
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-18T07:17:48.683432600-05:00[America/Toronto]", comments = "Generator version: 7.10.0")
public class TicketDTO {
  public static final String SERIALIZED_NAME_TICKET_I_D = "ticketID";
  @SerializedName(SERIALIZED_NAME_TICKET_I_D)
  @javax.annotation.Nonnull
  private Integer ticketID;

  public static final String SERIALIZED_NAME_TITLE = "title";
  @SerializedName(SERIALIZED_NAME_TITLE)
  @javax.annotation.Nonnull
  private String title;

  /**
   * Statut actuel du ticket
   */
  @JsonAdapter(StatusEnum.Adapter.class)
  public enum StatusEnum {
    OUVERT("OUVERT"),
    
    ASSIGNE("ASSIGNE"),
    
    TERMINE("TERMINE"),
    
    FERME("FERME");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<StatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StatusEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return StatusEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      StatusEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nonnull
  private StatusEnum status;

  /**
   * Niveau de priorité du ticket
   */
  @JsonAdapter(PriorityEnum.Adapter.class)
  public enum PriorityEnum {
    BASSE("BASSE"),
    
    MOYENNE("MOYENNE"),
    
    HAUTE("HAUTE"),
    
    CRITIQUE("CRITIQUE");

    private String value;

    PriorityEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static PriorityEnum fromValue(String value) {
      for (PriorityEnum b : PriorityEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<PriorityEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final PriorityEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public PriorityEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return PriorityEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      PriorityEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_PRIORITY = "priority";
  @SerializedName(SERIALIZED_NAME_PRIORITY)
  @javax.annotation.Nonnull
  private PriorityEnum priority;

  public static final String SERIALIZED_NAME_CREATED_BY_NAME = "createdByName";
  @SerializedName(SERIALIZED_NAME_CREATED_BY_NAME)
  @javax.annotation.Nullable
  private String createdByName;

  public static final String SERIALIZED_NAME_ASSIGNED_TO_NAME = "assignedToName";
  @SerializedName(SERIALIZED_NAME_ASSIGNED_TO_NAME)
  @javax.annotation.Nullable
  private String assignedToName;

  public static final String SERIALIZED_NAME_ASSIGNED_USER_ID = "assignedUserId";
  @SerializedName(SERIALIZED_NAME_ASSIGNED_USER_ID)
  @javax.annotation.Nullable
  private Integer assignedUserId;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  @javax.annotation.Nullable
  private Description description;

  public static final String SERIALIZED_NAME_CREATION_DATE = "creationDate";
  @SerializedName(SERIALIZED_NAME_CREATION_DATE)
  @javax.annotation.Nonnull
  private OffsetDateTime creationDate;

  public static final String SERIALIZED_NAME_UPDATE_DATE = "updateDate";
  @SerializedName(SERIALIZED_NAME_UPDATE_DATE)
  @javax.annotation.Nullable
  private OffsetDateTime updateDate;

  public static final String SERIALIZED_NAME_COMMENTS = "comments";
  @SerializedName(SERIALIZED_NAME_COMMENTS)
  @javax.annotation.Nullable
  private List<String> comments = new ArrayList<>();

  public TicketDTO() {
  }

  public TicketDTO ticketID(@javax.annotation.Nonnull Integer ticketID) {
    this.ticketID = ticketID;
    return this;
  }

  /**
   * Identifiant unique du ticket
   * @return ticketID
   */
  @javax.annotation.Nonnull
  public Integer getTicketID() {
    return ticketID;
  }

  public void setTicketID(@javax.annotation.Nonnull Integer ticketID) {
    this.ticketID = ticketID;
  }


  public TicketDTO title(@javax.annotation.Nonnull String title) {
    this.title = title;
    return this;
  }

  /**
   * Titre du ticket
   * @return title
   */
  @javax.annotation.Nonnull
  public String getTitle() {
    return title;
  }

  public void setTitle(@javax.annotation.Nonnull String title) {
    this.title = title;
  }


  public TicketDTO status(@javax.annotation.Nonnull StatusEnum status) {
    this.status = status;
    return this;
  }

  /**
   * Statut actuel du ticket
   * @return status
   */
  @javax.annotation.Nonnull
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(@javax.annotation.Nonnull StatusEnum status) {
    this.status = status;
  }


  public TicketDTO priority(@javax.annotation.Nonnull PriorityEnum priority) {
    this.priority = priority;
    return this;
  }

  /**
   * Niveau de priorité du ticket
   * @return priority
   */
  @javax.annotation.Nonnull
  public PriorityEnum getPriority() {
    return priority;
  }

  public void setPriority(@javax.annotation.Nonnull PriorityEnum priority) {
    this.priority = priority;
  }


  public TicketDTO createdByName(@javax.annotation.Nullable String createdByName) {
    this.createdByName = createdByName;
    return this;
  }

  /**
   * Nom de l&#39;utilisateur qui a créé le ticket
   * @return createdByName
   */
  @javax.annotation.Nullable
  public String getCreatedByName() {
    return createdByName;
  }

  public void setCreatedByName(@javax.annotation.Nullable String createdByName) {
    this.createdByName = createdByName;
  }


  public TicketDTO assignedToName(@javax.annotation.Nullable String assignedToName) {
    this.assignedToName = assignedToName;
    return this;
  }

  /**
   * Nom de l&#39;utilisateur assigné (null si non assigné)
   * @return assignedToName
   */
  @javax.annotation.Nullable
  public String getAssignedToName() {
    return assignedToName;
  }

  public void setAssignedToName(@javax.annotation.Nullable String assignedToName) {
    this.assignedToName = assignedToName;
  }


  public TicketDTO assignedUserId(@javax.annotation.Nullable Integer assignedUserId) {
    this.assignedUserId = assignedUserId;
    return this;
  }

  /**
   * ID de l&#39;utilisateur assigné (0 si non assigné)
   * @return assignedUserId
   */
  @javax.annotation.Nullable
  public Integer getAssignedUserId() {
    return assignedUserId;
  }

  public void setAssignedUserId(@javax.annotation.Nullable Integer assignedUserId) {
    this.assignedUserId = assignedUserId;
  }


  public TicketDTO description(@javax.annotation.Nullable Description description) {
    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @javax.annotation.Nullable
  public Description getDescription() {
    return description;
  }

  public void setDescription(@javax.annotation.Nullable Description description) {
    this.description = description;
  }


  public TicketDTO creationDate(@javax.annotation.Nonnull OffsetDateTime creationDate) {
    this.creationDate = creationDate;
    return this;
  }

  /**
   * Date et heure de création du ticket
   * @return creationDate
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getCreationDate() {
    return creationDate;
  }

  public void setCreationDate(@javax.annotation.Nonnull OffsetDateTime creationDate) {
    this.creationDate = creationDate;
  }


  public TicketDTO updateDate(@javax.annotation.Nullable OffsetDateTime updateDate) {
    this.updateDate = updateDate;
    return this;
  }

  /**
   * Date et heure de dernière modification
   * @return updateDate
   */
  @javax.annotation.Nullable
  public OffsetDateTime getUpdateDate() {
    return updateDate;
  }

  public void setUpdateDate(@javax.annotation.Nullable OffsetDateTime updateDate) {
    this.updateDate = updateDate;
  }


  public TicketDTO comments(@javax.annotation.Nullable List<String> comments) {
    this.comments = comments;
    return this;
  }

  public TicketDTO addCommentsItem(String commentsItem) {
    if (this.comments == null) {
      this.comments = new ArrayList<>();
    }
    this.comments.add(commentsItem);
    return this;
  }

  /**
   * Liste des commentaires du ticket
   * @return comments
   */
  @javax.annotation.Nullable
  public List<String> getComments() {
    return comments;
  }

  public void setComments(@javax.annotation.Nullable List<String> comments) {
    this.comments = comments;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TicketDTO ticketDTO = (TicketDTO) o;
    return Objects.equals(this.ticketID, ticketDTO.ticketID) &&
        Objects.equals(this.title, ticketDTO.title) &&
        Objects.equals(this.status, ticketDTO.status) &&
        Objects.equals(this.priority, ticketDTO.priority) &&
        Objects.equals(this.createdByName, ticketDTO.createdByName) &&
        Objects.equals(this.assignedToName, ticketDTO.assignedToName) &&
        Objects.equals(this.assignedUserId, ticketDTO.assignedUserId) &&
        Objects.equals(this.description, ticketDTO.description) &&
        Objects.equals(this.creationDate, ticketDTO.creationDate) &&
        Objects.equals(this.updateDate, ticketDTO.updateDate) &&
        Objects.equals(this.comments, ticketDTO.comments);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(ticketID, title, status, priority, createdByName, assignedToName, assignedUserId, description, creationDate, updateDate, comments);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TicketDTO {\n");
    sb.append("    ticketID: ").append(toIndentedString(ticketID)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
    sb.append("    createdByName: ").append(toIndentedString(createdByName)).append("\n");
    sb.append("    assignedToName: ").append(toIndentedString(assignedToName)).append("\n");
    sb.append("    assignedUserId: ").append(toIndentedString(assignedUserId)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    creationDate: ").append(toIndentedString(creationDate)).append("\n");
    sb.append("    updateDate: ").append(toIndentedString(updateDate)).append("\n");
    sb.append("    comments: ").append(toIndentedString(comments)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("ticketID");
    openapiFields.add("title");
    openapiFields.add("status");
    openapiFields.add("priority");
    openapiFields.add("createdByName");
    openapiFields.add("assignedToName");
    openapiFields.add("assignedUserId");
    openapiFields.add("description");
    openapiFields.add("creationDate");
    openapiFields.add("updateDate");
    openapiFields.add("comments");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("ticketID");
    openapiRequiredFields.add("title");
    openapiRequiredFields.add("status");
    openapiRequiredFields.add("priority");
    openapiRequiredFields.add("creationDate");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to TicketDTO
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!TicketDTO.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in TicketDTO is not found in the empty JSON string", TicketDTO.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!TicketDTO.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `TicketDTO` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : TicketDTO.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("title").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `title` to be a primitive type in the JSON string but got `%s`", jsonObj.get("title").toString()));
      }
      if (!jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
      // validate the required field `status`
      StatusEnum.validateJsonElement(jsonObj.get("status"));
      if (!jsonObj.get("priority").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `priority` to be a primitive type in the JSON string but got `%s`", jsonObj.get("priority").toString()));
      }
      // validate the required field `priority`
      PriorityEnum.validateJsonElement(jsonObj.get("priority"));
      if ((jsonObj.get("createdByName") != null && !jsonObj.get("createdByName").isJsonNull()) && !jsonObj.get("createdByName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `createdByName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("createdByName").toString()));
      }
      if ((jsonObj.get("assignedToName") != null && !jsonObj.get("assignedToName").isJsonNull()) && !jsonObj.get("assignedToName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `assignedToName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("assignedToName").toString()));
      }
      // validate the optional field `description`
      if (jsonObj.get("description") != null && !jsonObj.get("description").isJsonNull()) {
        Description.validateJsonElement(jsonObj.get("description"));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("comments") != null && !jsonObj.get("comments").isJsonNull() && !jsonObj.get("comments").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `comments` to be an array in the JSON string but got `%s`", jsonObj.get("comments").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TicketDTO.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TicketDTO' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TicketDTO> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TicketDTO.class));

       return (TypeAdapter<T>) new TypeAdapter<TicketDTO>() {
           @Override
           public void write(JsonWriter out, TicketDTO value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public TicketDTO read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of TicketDTO given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of TicketDTO
   * @throws IOException if the JSON string is invalid with respect to TicketDTO
   */
  public static TicketDTO fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TicketDTO.class);
  }

  /**
   * Convert an instance of TicketDTO to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

