/*
 * Système de Gestion de Tickets (SBIR), API REST
 * API REST pour le système de gestion de tickets développé en Java pour le cours 6GEI311, Architecture Logicielle  Auteurs: Il'aina Ratefinanahary et Samuel Brassard, UQAC Automne 2025 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: iratefinan@etu.uqac.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetTicketImages200Response
 */
public class GetTicketImages200ResponseTest {
    private final GetTicketImages200Response model = new GetTicketImages200Response();

    /**
     * Model tests for GetTicketImages200Response
     */
    @Test
    public void testGetTicketImages200Response() {
        // TODO: test GetTicketImages200Response
    }

    /**
     * Test the property 'ticketId'
     */
    @Test
    public void ticketIdTest() {
        // TODO: test ticketId
    }

    /**
     * Test the property 'imagePaths'
     */
    @Test
    public void imagePathsTest() {
        // TODO: test imagePaths
    }

}
