/*
 * Système de Gestion de Tickets (SBIR), API REST
 * API REST pour le système de gestion de tickets développé en Java pour le cours 6GEI311, Architecture Logicielle  Auteurs: Il'aina Ratefinanahary et Samuel Brassard, UQAC Automne 2025 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: iratefinan@etu.uqac.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiCallback;
import org.openapitools.client.ApiClient;
import org.openapitools.client.ApiException;
import org.openapitools.client.ApiResponse;
import org.openapitools.client.Configuration;
import org.openapitools.client.Pair;

import com.google.gson.reflect.TypeToken;

import java.io.File;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ExportApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public ExportApi() {
        this(Configuration.getDefaultApiClient());
    }

    public ExportApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for exportTicketToPDF
     * @param ticketId Identifiant unique du ticket (required)
     * @param userId ID de l&#39;utilisateur demandant l&#39;export (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Export PDF généré avec succès </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ressource non trouvée </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Accès refusé (permissions insuffisantes) </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erreur interne du serveur </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call exportTicketToPDFCall(Integer ticketId, Integer userId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/tickets/{ticketId}/export/pdf"
            .replace("{" + "ticketId" + "}", localVarApiClient.escapeString(ticketId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (userId != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("userId", userId));
        }

        final String[] localVarAccepts = {
            "application/pdf",
            "text/plain",
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call exportTicketToPDFValidateBeforeCall(Integer ticketId, Integer userId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'ticketId' is set
        if (ticketId == null) {
            throw new ApiException("Missing the required parameter 'ticketId' when calling exportTicketToPDF(Async)");
        }

        return exportTicketToPDFCall(ticketId, userId, _callback);

    }

    /**
     * Exporte un ticket en PDF
     * Génère et exporte le contenu d&#39;un ticket en format PDF. Utilise le pattern Strategy (PDFExporter) côté serveur. 
     * @param ticketId Identifiant unique du ticket (required)
     * @param userId ID de l&#39;utilisateur demandant l&#39;export (optional)
     * @return File
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Export PDF généré avec succès </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ressource non trouvée </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Accès refusé (permissions insuffisantes) </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erreur interne du serveur </td><td>  -  </td></tr>
     </table>
     */
    public File exportTicketToPDF(Integer ticketId, Integer userId) throws ApiException {
        ApiResponse<File> localVarResp = exportTicketToPDFWithHttpInfo(ticketId, userId);
        return localVarResp.getData();
    }

    /**
     * Exporte un ticket en PDF
     * Génère et exporte le contenu d&#39;un ticket en format PDF. Utilise le pattern Strategy (PDFExporter) côté serveur. 
     * @param ticketId Identifiant unique du ticket (required)
     * @param userId ID de l&#39;utilisateur demandant l&#39;export (optional)
     * @return ApiResponse&lt;File&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Export PDF généré avec succès </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ressource non trouvée </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Accès refusé (permissions insuffisantes) </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erreur interne du serveur </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<File> exportTicketToPDFWithHttpInfo(Integer ticketId, Integer userId) throws ApiException {
        okhttp3.Call localVarCall = exportTicketToPDFValidateBeforeCall(ticketId, userId, null);
        Type localVarReturnType = new TypeToken<File>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Exporte un ticket en PDF (asynchronously)
     * Génère et exporte le contenu d&#39;un ticket en format PDF. Utilise le pattern Strategy (PDFExporter) côté serveur. 
     * @param ticketId Identifiant unique du ticket (required)
     * @param userId ID de l&#39;utilisateur demandant l&#39;export (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Export PDF généré avec succès </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ressource non trouvée </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Accès refusé (permissions insuffisantes) </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erreur interne du serveur </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call exportTicketToPDFAsync(Integer ticketId, Integer userId, final ApiCallback<File> _callback) throws ApiException {

        okhttp3.Call localVarCall = exportTicketToPDFValidateBeforeCall(ticketId, userId, _callback);
        Type localVarReturnType = new TypeToken<File>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
