/*
 * Système de Gestion de Tickets (SBIR), API REST
 * API REST pour le système de gestion de tickets développé en Java pour le cours 6GEI311, Architecture Logicielle  Auteurs: Il'aina Ratefinanahary et Samuel Brassard, UQAC Automne 2025 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: iratefinan@etu.uqac.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiCallback;
import org.openapitools.client.ApiClient;
import org.openapitools.client.ApiException;
import org.openapitools.client.ApiResponse;
import org.openapitools.client.Configuration;
import org.openapitools.client.Pair;
import org.openapitools.client.ProgressRequestBody;
import org.openapitools.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import org.openapitools.client.model.AddImageRequest;
import org.openapitools.client.model.AddVideoRequest;
import org.openapitools.client.model.ErrorResponse;
import org.openapitools.client.model.GetTicketImages200Response;
import org.openapitools.client.model.TicketDTO;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class MediaApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public MediaApi() {
        this(Configuration.getDefaultApiClient());
    }

    public MediaApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for addImageToTicket
     * @param ticketId Identifiant unique du ticket (required)
     * @param addImageRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Image ajoutée avec succès </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ressource non trouvée </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Requête invalide (validation échouée) </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erreur interne du serveur </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call addImageToTicketCall(Integer ticketId, AddImageRequest addImageRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = addImageRequest;

        // create path and map variables
        String localVarPath = "/tickets/{ticketId}/ajoutImage"
            .replace("{" + "ticketId" + "}", localVarApiClient.escapeString(ticketId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call addImageToTicketValidateBeforeCall(Integer ticketId, AddImageRequest addImageRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'ticketId' is set
        if (ticketId == null) {
            throw new ApiException("Missing the required parameter 'ticketId' when calling addImageToTicket(Async)");
        }

        // verify the required parameter 'addImageRequest' is set
        if (addImageRequest == null) {
            throw new ApiException("Missing the required parameter 'addImageRequest' when calling addImageToTicket(Async)");
        }

        return addImageToTicketCall(ticketId, addImageRequest, _callback);

    }

    /**
     * Ajoute une image à la description du ticket
     * Ajoute un chemin d&#39;image à la description d&#39;un ticket spécifique
     * @param ticketId Identifiant unique du ticket (required)
     * @param addImageRequest  (required)
     * @return TicketDTO
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Image ajoutée avec succès </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ressource non trouvée </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Requête invalide (validation échouée) </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erreur interne du serveur </td><td>  -  </td></tr>
     </table>
     */
    public TicketDTO addImageToTicket(Integer ticketId, AddImageRequest addImageRequest) throws ApiException {
        ApiResponse<TicketDTO> localVarResp = addImageToTicketWithHttpInfo(ticketId, addImageRequest);
        return localVarResp.getData();
    }

    /**
     * Ajoute une image à la description du ticket
     * Ajoute un chemin d&#39;image à la description d&#39;un ticket spécifique
     * @param ticketId Identifiant unique du ticket (required)
     * @param addImageRequest  (required)
     * @return ApiResponse&lt;TicketDTO&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Image ajoutée avec succès </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ressource non trouvée </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Requête invalide (validation échouée) </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erreur interne du serveur </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<TicketDTO> addImageToTicketWithHttpInfo(Integer ticketId, AddImageRequest addImageRequest) throws ApiException {
        okhttp3.Call localVarCall = addImageToTicketValidateBeforeCall(ticketId, addImageRequest, null);
        Type localVarReturnType = new TypeToken<TicketDTO>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Ajoute une image à la description du ticket (asynchronously)
     * Ajoute un chemin d&#39;image à la description d&#39;un ticket spécifique
     * @param ticketId Identifiant unique du ticket (required)
     * @param addImageRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Image ajoutée avec succès </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ressource non trouvée </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Requête invalide (validation échouée) </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erreur interne du serveur </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call addImageToTicketAsync(Integer ticketId, AddImageRequest addImageRequest, final ApiCallback<TicketDTO> _callback) throws ApiException {

        okhttp3.Call localVarCall = addImageToTicketValidateBeforeCall(ticketId, addImageRequest, _callback);
        Type localVarReturnType = new TypeToken<TicketDTO>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for addVideoToTicket
     * @param ticketId Identifiant unique du ticket (required)
     * @param addVideoRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Vidéo ajoutée avec succès </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ressource non trouvée </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Requête invalide (validation échouée) </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erreur interne du serveur </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call addVideoToTicketCall(Integer ticketId, AddVideoRequest addVideoRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = addVideoRequest;

        // create path and map variables
        String localVarPath = "/tickets/{ticketId}/ajoutVideo"
            .replace("{" + "ticketId" + "}", localVarApiClient.escapeString(ticketId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call addVideoToTicketValidateBeforeCall(Integer ticketId, AddVideoRequest addVideoRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'ticketId' is set
        if (ticketId == null) {
            throw new ApiException("Missing the required parameter 'ticketId' when calling addVideoToTicket(Async)");
        }

        // verify the required parameter 'addVideoRequest' is set
        if (addVideoRequest == null) {
            throw new ApiException("Missing the required parameter 'addVideoRequest' when calling addVideoToTicket(Async)");
        }

        return addVideoToTicketCall(ticketId, addVideoRequest, _callback);

    }

    /**
     * Ajoute une vidéo à la description du ticket
     * Ajoute un chemin de vidéo à la description d&#39;un ticket spécifique
     * @param ticketId Identifiant unique du ticket (required)
     * @param addVideoRequest  (required)
     * @return TicketDTO
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Vidéo ajoutée avec succès </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ressource non trouvée </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Requête invalide (validation échouée) </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erreur interne du serveur </td><td>  -  </td></tr>
     </table>
     */
    public TicketDTO addVideoToTicket(Integer ticketId, AddVideoRequest addVideoRequest) throws ApiException {
        ApiResponse<TicketDTO> localVarResp = addVideoToTicketWithHttpInfo(ticketId, addVideoRequest);
        return localVarResp.getData();
    }

    /**
     * Ajoute une vidéo à la description du ticket
     * Ajoute un chemin de vidéo à la description d&#39;un ticket spécifique
     * @param ticketId Identifiant unique du ticket (required)
     * @param addVideoRequest  (required)
     * @return ApiResponse&lt;TicketDTO&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Vidéo ajoutée avec succès </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ressource non trouvée </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Requête invalide (validation échouée) </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erreur interne du serveur </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<TicketDTO> addVideoToTicketWithHttpInfo(Integer ticketId, AddVideoRequest addVideoRequest) throws ApiException {
        okhttp3.Call localVarCall = addVideoToTicketValidateBeforeCall(ticketId, addVideoRequest, null);
        Type localVarReturnType = new TypeToken<TicketDTO>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Ajoute une vidéo à la description du ticket (asynchronously)
     * Ajoute un chemin de vidéo à la description d&#39;un ticket spécifique
     * @param ticketId Identifiant unique du ticket (required)
     * @param addVideoRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Vidéo ajoutée avec succès </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ressource non trouvée </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Requête invalide (validation échouée) </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erreur interne du serveur </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call addVideoToTicketAsync(Integer ticketId, AddVideoRequest addVideoRequest, final ApiCallback<TicketDTO> _callback) throws ApiException {

        okhttp3.Call localVarCall = addVideoToTicketValidateBeforeCall(ticketId, addVideoRequest, _callback);
        Type localVarReturnType = new TypeToken<TicketDTO>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getTicketImages
     * @param ticketId Identifiant unique du ticket (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Liste des images récupérée avec succès </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ressource non trouvée </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erreur interne du serveur </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getTicketImagesCall(Integer ticketId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/tickets/{ticketId}/voirImage"
            .replace("{" + "ticketId" + "}", localVarApiClient.escapeString(ticketId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getTicketImagesValidateBeforeCall(Integer ticketId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'ticketId' is set
        if (ticketId == null) {
            throw new ApiException("Missing the required parameter 'ticketId' when calling getTicketImages(Async)");
        }

        return getTicketImagesCall(ticketId, _callback);

    }

    /**
     * Récupère les images d&#39;un ticket
     * Retourne la liste de tous les chemins d&#39;images associés à la description du ticket
     * @param ticketId Identifiant unique du ticket (required)
     * @return GetTicketImages200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Liste des images récupérée avec succès </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ressource non trouvée </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erreur interne du serveur </td><td>  -  </td></tr>
     </table>
     */
    public GetTicketImages200Response getTicketImages(Integer ticketId) throws ApiException {
        ApiResponse<GetTicketImages200Response> localVarResp = getTicketImagesWithHttpInfo(ticketId);
        return localVarResp.getData();
    }

    /**
     * Récupère les images d&#39;un ticket
     * Retourne la liste de tous les chemins d&#39;images associés à la description du ticket
     * @param ticketId Identifiant unique du ticket (required)
     * @return ApiResponse&lt;GetTicketImages200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Liste des images récupérée avec succès </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ressource non trouvée </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erreur interne du serveur </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<GetTicketImages200Response> getTicketImagesWithHttpInfo(Integer ticketId) throws ApiException {
        okhttp3.Call localVarCall = getTicketImagesValidateBeforeCall(ticketId, null);
        Type localVarReturnType = new TypeToken<GetTicketImages200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Récupère les images d&#39;un ticket (asynchronously)
     * Retourne la liste de tous les chemins d&#39;images associés à la description du ticket
     * @param ticketId Identifiant unique du ticket (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Liste des images récupérée avec succès </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ressource non trouvée </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erreur interne du serveur </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getTicketImagesAsync(Integer ticketId, final ApiCallback<GetTicketImages200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = getTicketImagesValidateBeforeCall(ticketId, _callback);
        Type localVarReturnType = new TypeToken<GetTicketImages200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
