/*
 * Système de Gestion de Tickets (SBIR), API REST
 * API REST pour le système de gestion de tickets développé en Java pour le cours 6GEI311, Architecture Logicielle  Auteurs: Il'aina Ratefinanahary et Samuel Brassard, UQAC Automne 2025 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: iratefinan@etu.uqac.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiCallback;
import org.openapitools.client.ApiClient;
import org.openapitools.client.ApiException;
import org.openapitools.client.ApiResponse;
import org.openapitools.client.Configuration;
import org.openapitools.client.Pair;

import com.google.gson.reflect.TypeToken;

import org.openapitools.client.model.StatusUpdateDTO;
import org.openapitools.client.model.TicketDTO;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class StatusApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public StatusApi() {
        this(Configuration.getDefaultApiClient());
    }

    public StatusApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for getAvailableTransitions
     * @param ticketId Identifiant unique du ticket (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Liste des transitions disponibles </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ressource non trouvée </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erreur interne du serveur </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getAvailableTransitionsCall(Integer ticketId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/tickets/{ticketId}/status"
            .replace("{" + "ticketId" + "}", localVarApiClient.escapeString(ticketId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getAvailableTransitionsValidateBeforeCall(Integer ticketId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'ticketId' is set
        if (ticketId == null) {
            throw new ApiException("Missing the required parameter 'ticketId' when calling getAvailableTransitions(Async)");
        }

        return getAvailableTransitionsCall(ticketId, _callback);

    }

    /**
     * Obtenir les transitions disponibles
     * Retourne la liste des statuts vers lesquels une transition est possible
     * @param ticketId Identifiant unique du ticket (required)
     * @return List&lt;String&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Liste des transitions disponibles </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ressource non trouvée </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erreur interne du serveur </td><td>  -  </td></tr>
     </table>
     */
    public List<String> getAvailableTransitions(Integer ticketId) throws ApiException {
        ApiResponse<List<String>> localVarResp = getAvailableTransitionsWithHttpInfo(ticketId);
        return localVarResp.getData();
    }

    /**
     * Obtenir les transitions disponibles
     * Retourne la liste des statuts vers lesquels une transition est possible
     * @param ticketId Identifiant unique du ticket (required)
     * @return ApiResponse&lt;List&lt;String&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Liste des transitions disponibles </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ressource non trouvée </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erreur interne du serveur </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<List<String>> getAvailableTransitionsWithHttpInfo(Integer ticketId) throws ApiException {
        okhttp3.Call localVarCall = getAvailableTransitionsValidateBeforeCall(ticketId, null);
        Type localVarReturnType = new TypeToken<List<String>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Obtenir les transitions disponibles (asynchronously)
     * Retourne la liste des statuts vers lesquels une transition est possible
     * @param ticketId Identifiant unique du ticket (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Liste des transitions disponibles </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ressource non trouvée </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erreur interne du serveur </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getAvailableTransitionsAsync(Integer ticketId, final ApiCallback<List<String>> _callback) throws ApiException {

        okhttp3.Call localVarCall = getAvailableTransitionsValidateBeforeCall(ticketId, _callback);
        Type localVarReturnType = new TypeToken<List<String>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for updateTicketStatus
     * @param ticketId Identifiant unique du ticket (required)
     * @param statusUpdateDTO  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Statut mis à jour avec succès </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Transition de statut invalide </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ressource non trouvée </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Accès refusé (permissions insuffisantes) </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erreur interne du serveur </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateTicketStatusCall(Integer ticketId, StatusUpdateDTO statusUpdateDTO, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = statusUpdateDTO;

        // create path and map variables
        String localVarPath = "/tickets/{ticketId}/status"
            .replace("{" + "ticketId" + "}", localVarApiClient.escapeString(ticketId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call updateTicketStatusValidateBeforeCall(Integer ticketId, StatusUpdateDTO statusUpdateDTO, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'ticketId' is set
        if (ticketId == null) {
            throw new ApiException("Missing the required parameter 'ticketId' when calling updateTicketStatus(Async)");
        }

        // verify the required parameter 'statusUpdateDTO' is set
        if (statusUpdateDTO == null) {
            throw new ApiException("Missing the required parameter 'statusUpdateDTO' when calling updateTicketStatus(Async)");
        }

        return updateTicketStatusCall(ticketId, statusUpdateDTO, _callback);

    }

    /**
     * Modifie le statut d&#39;un ticket
     * Met à jour le statut d&#39;un ticket spécifique avec validation des transitions.  Transitions autorisées : - OUVERT → ASSIGNE, FERME - ASSIGNE → TERMINE, FERME - TERMINE/FERME → (états finaux, aucune transition)  Seuls les admins et développeurs peuvent changer les statuts. 
     * @param ticketId Identifiant unique du ticket (required)
     * @param statusUpdateDTO  (required)
     * @return TicketDTO
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Statut mis à jour avec succès </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Transition de statut invalide </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ressource non trouvée </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Accès refusé (permissions insuffisantes) </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erreur interne du serveur </td><td>  -  </td></tr>
     </table>
     */
    public TicketDTO updateTicketStatus(Integer ticketId, StatusUpdateDTO statusUpdateDTO) throws ApiException {
        ApiResponse<TicketDTO> localVarResp = updateTicketStatusWithHttpInfo(ticketId, statusUpdateDTO);
        return localVarResp.getData();
    }

    /**
     * Modifie le statut d&#39;un ticket
     * Met à jour le statut d&#39;un ticket spécifique avec validation des transitions.  Transitions autorisées : - OUVERT → ASSIGNE, FERME - ASSIGNE → TERMINE, FERME - TERMINE/FERME → (états finaux, aucune transition)  Seuls les admins et développeurs peuvent changer les statuts. 
     * @param ticketId Identifiant unique du ticket (required)
     * @param statusUpdateDTO  (required)
     * @return ApiResponse&lt;TicketDTO&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Statut mis à jour avec succès </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Transition de statut invalide </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ressource non trouvée </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Accès refusé (permissions insuffisantes) </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erreur interne du serveur </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<TicketDTO> updateTicketStatusWithHttpInfo(Integer ticketId, StatusUpdateDTO statusUpdateDTO) throws ApiException {
        okhttp3.Call localVarCall = updateTicketStatusValidateBeforeCall(ticketId, statusUpdateDTO, null);
        Type localVarReturnType = new TypeToken<TicketDTO>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Modifie le statut d&#39;un ticket (asynchronously)
     * Met à jour le statut d&#39;un ticket spécifique avec validation des transitions.  Transitions autorisées : - OUVERT → ASSIGNE, FERME - ASSIGNE → TERMINE, FERME - TERMINE/FERME → (états finaux, aucune transition)  Seuls les admins et développeurs peuvent changer les statuts. 
     * @param ticketId Identifiant unique du ticket (required)
     * @param statusUpdateDTO  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Statut mis à jour avec succès </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Transition de statut invalide </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ressource non trouvée </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Accès refusé (permissions insuffisantes) </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erreur interne du serveur </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateTicketStatusAsync(Integer ticketId, StatusUpdateDTO statusUpdateDTO, final ApiCallback<TicketDTO> _callback) throws ApiException {

        okhttp3.Call localVarCall = updateTicketStatusValidateBeforeCall(ticketId, statusUpdateDTO, _callback);
        Type localVarReturnType = new TypeToken<TicketDTO>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
