/*
 * Système de Gestion de Tickets (SBIR), API REST
 * API REST pour le système de gestion de tickets développé en Java pour le cours 6GEI311, Architecture Logicielle  Auteurs: Il'aina Ratefinanahary et Samuel Brassard, UQAC Automne 2025 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: iratefinan@etu.uqac.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiCallback;
import org.openapitools.client.ApiClient;
import org.openapitools.client.ApiException;
import org.openapitools.client.ApiResponse;
import org.openapitools.client.Configuration;
import org.openapitools.client.Pair;

import com.google.gson.reflect.TypeToken;

import org.openapitools.client.model.AssignmentDTO;
import org.openapitools.client.model.CloseTicketRequest;
import org.openapitools.client.model.CreateTicketRequest;
import org.openapitools.client.model.Description;
import org.openapitools.client.model.TicketDTO;
import org.openapitools.client.model.UnassignTicketRequest;
import org.openapitools.client.model.UpdateTicketPriorityRequest;
import org.openapitools.client.model.UpdateTicketRequest;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class TicketsApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public TicketsApi() {
        this(Configuration.getDefaultApiClient());
    }

    public TicketsApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for assignTicket
     * @param ticketId Identifiant unique du ticket (required)
     * @param assignmentDTO  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Ticket assigné avec succès </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Requête invalide (validation échouée) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ressource non trouvée </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Accès refusé (permissions insuffisantes) </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erreur interne du serveur </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call assignTicketCall(Integer ticketId, AssignmentDTO assignmentDTO, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = assignmentDTO;

        // create path and map variables
        String localVarPath = "/tickets/{ticketId}/assign"
            .replace("{" + "ticketId" + "}", localVarApiClient.escapeString(ticketId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call assignTicketValidateBeforeCall(Integer ticketId, AssignmentDTO assignmentDTO, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'ticketId' is set
        if (ticketId == null) {
            throw new ApiException("Missing the required parameter 'ticketId' when calling assignTicket(Async)");
        }

        // verify the required parameter 'assignmentDTO' is set
        if (assignmentDTO == null) {
            throw new ApiException("Missing the required parameter 'assignmentDTO' when calling assignTicket(Async)");
        }

        return assignTicketCall(ticketId, assignmentDTO, _callback);

    }

    /**
     * Assigne un ticket à un utilisateur
     * Assigne un ticket à un utilisateur spécifique. Change automatiquement le statut du ticket à ASSIGNE. Seuls les admins peuvent assigner des tickets. 
     * @param ticketId Identifiant unique du ticket (required)
     * @param assignmentDTO  (required)
     * @return TicketDTO
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Ticket assigné avec succès </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Requête invalide (validation échouée) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ressource non trouvée </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Accès refusé (permissions insuffisantes) </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erreur interne du serveur </td><td>  -  </td></tr>
     </table>
     */
    public TicketDTO assignTicket(Integer ticketId, AssignmentDTO assignmentDTO) throws ApiException {
        ApiResponse<TicketDTO> localVarResp = assignTicketWithHttpInfo(ticketId, assignmentDTO);
        return localVarResp.getData();
    }

    /**
     * Assigne un ticket à un utilisateur
     * Assigne un ticket à un utilisateur spécifique. Change automatiquement le statut du ticket à ASSIGNE. Seuls les admins peuvent assigner des tickets. 
     * @param ticketId Identifiant unique du ticket (required)
     * @param assignmentDTO  (required)
     * @return ApiResponse&lt;TicketDTO&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Ticket assigné avec succès </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Requête invalide (validation échouée) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ressource non trouvée </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Accès refusé (permissions insuffisantes) </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erreur interne du serveur </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<TicketDTO> assignTicketWithHttpInfo(Integer ticketId, AssignmentDTO assignmentDTO) throws ApiException {
        okhttp3.Call localVarCall = assignTicketValidateBeforeCall(ticketId, assignmentDTO, null);
        Type localVarReturnType = new TypeToken<TicketDTO>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Assigne un ticket à un utilisateur (asynchronously)
     * Assigne un ticket à un utilisateur spécifique. Change automatiquement le statut du ticket à ASSIGNE. Seuls les admins peuvent assigner des tickets. 
     * @param ticketId Identifiant unique du ticket (required)
     * @param assignmentDTO  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Ticket assigné avec succès </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Requête invalide (validation échouée) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ressource non trouvée </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Accès refusé (permissions insuffisantes) </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erreur interne du serveur </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call assignTicketAsync(Integer ticketId, AssignmentDTO assignmentDTO, final ApiCallback<TicketDTO> _callback) throws ApiException {

        okhttp3.Call localVarCall = assignTicketValidateBeforeCall(ticketId, assignmentDTO, _callback);
        Type localVarReturnType = new TypeToken<TicketDTO>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for closeTicket
     * @param ticketId Identifiant unique du ticket (required)
     * @param closeTicketRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Ticket fermé avec succès </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Accès refusé (permissions insuffisantes) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ressource non trouvée </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erreur interne du serveur </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call closeTicketCall(Integer ticketId, CloseTicketRequest closeTicketRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = closeTicketRequest;

        // create path and map variables
        String localVarPath = "/tickets/{ticketId}/close"
            .replace("{" + "ticketId" + "}", localVarApiClient.escapeString(ticketId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call closeTicketValidateBeforeCall(Integer ticketId, CloseTicketRequest closeTicketRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'ticketId' is set
        if (ticketId == null) {
            throw new ApiException("Missing the required parameter 'ticketId' when calling closeTicket(Async)");
        }

        // verify the required parameter 'closeTicketRequest' is set
        if (closeTicketRequest == null) {
            throw new ApiException("Missing the required parameter 'closeTicketRequest' when calling closeTicket(Async)");
        }

        return closeTicketCall(ticketId, closeTicketRequest, _callback);

    }

    /**
     * Ferme/termine un ticket
     * Marque un ticket comme terminé
     * @param ticketId Identifiant unique du ticket (required)
     * @param closeTicketRequest  (required)
     * @return TicketDTO
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Ticket fermé avec succès </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Accès refusé (permissions insuffisantes) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ressource non trouvée </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erreur interne du serveur </td><td>  -  </td></tr>
     </table>
     */
    public TicketDTO closeTicket(Integer ticketId, CloseTicketRequest closeTicketRequest) throws ApiException {
        ApiResponse<TicketDTO> localVarResp = closeTicketWithHttpInfo(ticketId, closeTicketRequest);
        return localVarResp.getData();
    }

    /**
     * Ferme/termine un ticket
     * Marque un ticket comme terminé
     * @param ticketId Identifiant unique du ticket (required)
     * @param closeTicketRequest  (required)
     * @return ApiResponse&lt;TicketDTO&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Ticket fermé avec succès </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Accès refusé (permissions insuffisantes) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ressource non trouvée </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erreur interne du serveur </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<TicketDTO> closeTicketWithHttpInfo(Integer ticketId, CloseTicketRequest closeTicketRequest) throws ApiException {
        okhttp3.Call localVarCall = closeTicketValidateBeforeCall(ticketId, closeTicketRequest, null);
        Type localVarReturnType = new TypeToken<TicketDTO>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Ferme/termine un ticket (asynchronously)
     * Marque un ticket comme terminé
     * @param ticketId Identifiant unique du ticket (required)
     * @param closeTicketRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Ticket fermé avec succès </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Accès refusé (permissions insuffisantes) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ressource non trouvée </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erreur interne du serveur </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call closeTicketAsync(Integer ticketId, CloseTicketRequest closeTicketRequest, final ApiCallback<TicketDTO> _callback) throws ApiException {

        okhttp3.Call localVarCall = closeTicketValidateBeforeCall(ticketId, closeTicketRequest, _callback);
        Type localVarReturnType = new TypeToken<TicketDTO>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for createTicket
     * @param createTicketRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Ticket créé avec succès </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Requête invalide (validation échouée) </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erreur interne du serveur </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createTicketCall(CreateTicketRequest createTicketRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = createTicketRequest;

        // create path and map variables
        String localVarPath = "/tickets";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call createTicketValidateBeforeCall(CreateTicketRequest createTicketRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'createTicketRequest' is set
        if (createTicketRequest == null) {
            throw new ApiException("Missing the required parameter 'createTicketRequest' when calling createTicket(Async)");
        }

        return createTicketCall(createTicketRequest, _callback);

    }

    /**
     * Crée un nouveau ticket
     * Crée un nouveau ticket dans le système
     * @param createTicketRequest  (required)
     * @return TicketDTO
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Ticket créé avec succès </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Requête invalide (validation échouée) </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erreur interne du serveur </td><td>  -  </td></tr>
     </table>
     */
    public TicketDTO createTicket(CreateTicketRequest createTicketRequest) throws ApiException {
        ApiResponse<TicketDTO> localVarResp = createTicketWithHttpInfo(createTicketRequest);
        return localVarResp.getData();
    }

    /**
     * Crée un nouveau ticket
     * Crée un nouveau ticket dans le système
     * @param createTicketRequest  (required)
     * @return ApiResponse&lt;TicketDTO&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Ticket créé avec succès </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Requête invalide (validation échouée) </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erreur interne du serveur </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<TicketDTO> createTicketWithHttpInfo(CreateTicketRequest createTicketRequest) throws ApiException {
        okhttp3.Call localVarCall = createTicketValidateBeforeCall(createTicketRequest, null);
        Type localVarReturnType = new TypeToken<TicketDTO>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Crée un nouveau ticket (asynchronously)
     * Crée un nouveau ticket dans le système
     * @param createTicketRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Ticket créé avec succès </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Requête invalide (validation échouée) </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erreur interne du serveur </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createTicketAsync(CreateTicketRequest createTicketRequest, final ApiCallback<TicketDTO> _callback) throws ApiException {

        okhttp3.Call localVarCall = createTicketValidateBeforeCall(createTicketRequest, _callback);
        Type localVarReturnType = new TypeToken<TicketDTO>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for deleteTicket
     * @param ticketId Identifiant unique du ticket (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Ticket supprimé avec succès </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ressource non trouvée </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Accès refusé (permissions insuffisantes) </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erreur interne du serveur </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteTicketCall(Integer ticketId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/tickets/{ticketId}"
            .replace("{" + "ticketId" + "}", localVarApiClient.escapeString(ticketId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call deleteTicketValidateBeforeCall(Integer ticketId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'ticketId' is set
        if (ticketId == null) {
            throw new ApiException("Missing the required parameter 'ticketId' when calling deleteTicket(Async)");
        }

        return deleteTicketCall(ticketId, _callback);

    }

    /**
     * Supprime un ticket
     * Supprime un ticket. Seuls les administrateurs peuvent supprimer des tickets. 
     * @param ticketId Identifiant unique du ticket (required)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Ticket supprimé avec succès </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ressource non trouvée </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Accès refusé (permissions insuffisantes) </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erreur interne du serveur </td><td>  -  </td></tr>
     </table>
     */
    public void deleteTicket(Integer ticketId) throws ApiException {
        deleteTicketWithHttpInfo(ticketId);
    }

    /**
     * Supprime un ticket
     * Supprime un ticket. Seuls les administrateurs peuvent supprimer des tickets. 
     * @param ticketId Identifiant unique du ticket (required)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Ticket supprimé avec succès </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ressource non trouvée </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Accès refusé (permissions insuffisantes) </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erreur interne du serveur </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> deleteTicketWithHttpInfo(Integer ticketId) throws ApiException {
        okhttp3.Call localVarCall = deleteTicketValidateBeforeCall(ticketId, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * Supprime un ticket (asynchronously)
     * Supprime un ticket. Seuls les administrateurs peuvent supprimer des tickets. 
     * @param ticketId Identifiant unique du ticket (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Ticket supprimé avec succès </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ressource non trouvée </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Accès refusé (permissions insuffisantes) </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erreur interne du serveur </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteTicketAsync(Integer ticketId, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = deleteTicketValidateBeforeCall(ticketId, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
    /**
     * Build call for getAllTickets
     * @param status Filtrer par statut (optional)
     * @param assignedTo Filtrer par utilisateur assigné (ID) (optional)
     * @param priority Filtrer par priorité (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Liste des tickets récupérée avec succès </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erreur interne du serveur </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getAllTicketsCall(String status, Integer assignedTo, String priority, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/tickets";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (status != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("status", status));
        }

        if (assignedTo != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("assignedTo", assignedTo));
        }

        if (priority != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("priority", priority));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getAllTicketsValidateBeforeCall(String status, Integer assignedTo, String priority, final ApiCallback _callback) throws ApiException {
        return getAllTicketsCall(status, assignedTo, priority, _callback);

    }

    /**
     * Liste tous les tickets
     * Retourne la liste de tous les tickets du système avec filtrage optionnel
     * @param status Filtrer par statut (optional)
     * @param assignedTo Filtrer par utilisateur assigné (ID) (optional)
     * @param priority Filtrer par priorité (optional)
     * @return List&lt;TicketDTO&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Liste des tickets récupérée avec succès </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erreur interne du serveur </td><td>  -  </td></tr>
     </table>
     */
    public List<TicketDTO> getAllTickets(String status, Integer assignedTo, String priority) throws ApiException {
        ApiResponse<List<TicketDTO>> localVarResp = getAllTicketsWithHttpInfo(status, assignedTo, priority);
        return localVarResp.getData();
    }

    /**
     * Liste tous les tickets
     * Retourne la liste de tous les tickets du système avec filtrage optionnel
     * @param status Filtrer par statut (optional)
     * @param assignedTo Filtrer par utilisateur assigné (ID) (optional)
     * @param priority Filtrer par priorité (optional)
     * @return ApiResponse&lt;List&lt;TicketDTO&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Liste des tickets récupérée avec succès </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erreur interne du serveur </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<List<TicketDTO>> getAllTicketsWithHttpInfo(String status, Integer assignedTo, String priority) throws ApiException {
        okhttp3.Call localVarCall = getAllTicketsValidateBeforeCall(status, assignedTo, priority, null);
        Type localVarReturnType = new TypeToken<List<TicketDTO>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Liste tous les tickets (asynchronously)
     * Retourne la liste de tous les tickets du système avec filtrage optionnel
     * @param status Filtrer par statut (optional)
     * @param assignedTo Filtrer par utilisateur assigné (ID) (optional)
     * @param priority Filtrer par priorité (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Liste des tickets récupérée avec succès </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erreur interne du serveur </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getAllTicketsAsync(String status, Integer assignedTo, String priority, final ApiCallback<List<TicketDTO>> _callback) throws ApiException {

        okhttp3.Call localVarCall = getAllTicketsValidateBeforeCall(status, assignedTo, priority, _callback);
        Type localVarReturnType = new TypeToken<List<TicketDTO>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getTicketById
     * @param ticketId Identifiant unique du ticket (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Ticket trouvé </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ressource non trouvée </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Accès refusé (permissions insuffisantes) </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erreur interne du serveur </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getTicketByIdCall(Integer ticketId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/tickets/{ticketId}"
            .replace("{" + "ticketId" + "}", localVarApiClient.escapeString(ticketId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getTicketByIdValidateBeforeCall(Integer ticketId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'ticketId' is set
        if (ticketId == null) {
            throw new ApiException("Missing the required parameter 'ticketId' when calling getTicketById(Async)");
        }

        return getTicketByIdCall(ticketId, _callback);

    }

    /**
     * Récupère un ticket spécifique
     * Retourne les informations complètes d&#39;un ticket spécifique
     * @param ticketId Identifiant unique du ticket (required)
     * @return TicketDTO
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Ticket trouvé </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ressource non trouvée </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Accès refusé (permissions insuffisantes) </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erreur interne du serveur </td><td>  -  </td></tr>
     </table>
     */
    public TicketDTO getTicketById(Integer ticketId) throws ApiException {
        ApiResponse<TicketDTO> localVarResp = getTicketByIdWithHttpInfo(ticketId);
        return localVarResp.getData();
    }

    /**
     * Récupère un ticket spécifique
     * Retourne les informations complètes d&#39;un ticket spécifique
     * @param ticketId Identifiant unique du ticket (required)
     * @return ApiResponse&lt;TicketDTO&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Ticket trouvé </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ressource non trouvée </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Accès refusé (permissions insuffisantes) </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erreur interne du serveur </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<TicketDTO> getTicketByIdWithHttpInfo(Integer ticketId) throws ApiException {
        okhttp3.Call localVarCall = getTicketByIdValidateBeforeCall(ticketId, null);
        Type localVarReturnType = new TypeToken<TicketDTO>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Récupère un ticket spécifique (asynchronously)
     * Retourne les informations complètes d&#39;un ticket spécifique
     * @param ticketId Identifiant unique du ticket (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Ticket trouvé </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ressource non trouvée </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Accès refusé (permissions insuffisantes) </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erreur interne du serveur </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getTicketByIdAsync(Integer ticketId, final ApiCallback<TicketDTO> _callback) throws ApiException {

        okhttp3.Call localVarCall = getTicketByIdValidateBeforeCall(ticketId, _callback);
        Type localVarReturnType = new TypeToken<TicketDTO>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for unassignTicket
     * @param ticketId Identifiant unique du ticket (required)
     * @param unassignTicketRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Ticket désassigné avec succès </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ressource non trouvée </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Accès refusé (permissions insuffisantes) </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erreur interne du serveur </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call unassignTicketCall(Integer ticketId, UnassignTicketRequest unassignTicketRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = unassignTicketRequest;

        // create path and map variables
        String localVarPath = "/tickets/{ticketId}/unassign"
            .replace("{" + "ticketId" + "}", localVarApiClient.escapeString(ticketId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call unassignTicketValidateBeforeCall(Integer ticketId, UnassignTicketRequest unassignTicketRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'ticketId' is set
        if (ticketId == null) {
            throw new ApiException("Missing the required parameter 'ticketId' when calling unassignTicket(Async)");
        }

        // verify the required parameter 'unassignTicketRequest' is set
        if (unassignTicketRequest == null) {
            throw new ApiException("Missing the required parameter 'unassignTicketRequest' when calling unassignTicket(Async)");
        }

        return unassignTicketCall(ticketId, unassignTicketRequest, _callback);

    }

    /**
     * Désassigne un ticket
     * Retire l&#39;assignation d&#39;un ticket
     * @param ticketId Identifiant unique du ticket (required)
     * @param unassignTicketRequest  (required)
     * @return TicketDTO
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Ticket désassigné avec succès </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ressource non trouvée </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Accès refusé (permissions insuffisantes) </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erreur interne du serveur </td><td>  -  </td></tr>
     </table>
     */
    public TicketDTO unassignTicket(Integer ticketId, UnassignTicketRequest unassignTicketRequest) throws ApiException {
        ApiResponse<TicketDTO> localVarResp = unassignTicketWithHttpInfo(ticketId, unassignTicketRequest);
        return localVarResp.getData();
    }

    /**
     * Désassigne un ticket
     * Retire l&#39;assignation d&#39;un ticket
     * @param ticketId Identifiant unique du ticket (required)
     * @param unassignTicketRequest  (required)
     * @return ApiResponse&lt;TicketDTO&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Ticket désassigné avec succès </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ressource non trouvée </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Accès refusé (permissions insuffisantes) </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erreur interne du serveur </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<TicketDTO> unassignTicketWithHttpInfo(Integer ticketId, UnassignTicketRequest unassignTicketRequest) throws ApiException {
        okhttp3.Call localVarCall = unassignTicketValidateBeforeCall(ticketId, unassignTicketRequest, null);
        Type localVarReturnType = new TypeToken<TicketDTO>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Désassigne un ticket (asynchronously)
     * Retire l&#39;assignation d&#39;un ticket
     * @param ticketId Identifiant unique du ticket (required)
     * @param unassignTicketRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Ticket désassigné avec succès </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ressource non trouvée </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Accès refusé (permissions insuffisantes) </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erreur interne du serveur </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call unassignTicketAsync(Integer ticketId, UnassignTicketRequest unassignTicketRequest, final ApiCallback<TicketDTO> _callback) throws ApiException {

        okhttp3.Call localVarCall = unassignTicketValidateBeforeCall(ticketId, unassignTicketRequest, _callback);
        Type localVarReturnType = new TypeToken<TicketDTO>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for updateTicket
     * @param ticketId Identifiant unique du ticket (required)
     * @param updateTicketRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Ticket modifié avec succès </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Requête invalide (validation échouée) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ressource non trouvée </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Accès refusé (permissions insuffisantes) </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erreur interne du serveur </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateTicketCall(Integer ticketId, UpdateTicketRequest updateTicketRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = updateTicketRequest;

        // create path and map variables
        String localVarPath = "/tickets/{ticketId}"
            .replace("{" + "ticketId" + "}", localVarApiClient.escapeString(ticketId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call updateTicketValidateBeforeCall(Integer ticketId, UpdateTicketRequest updateTicketRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'ticketId' is set
        if (ticketId == null) {
            throw new ApiException("Missing the required parameter 'ticketId' when calling updateTicket(Async)");
        }

        // verify the required parameter 'updateTicketRequest' is set
        if (updateTicketRequest == null) {
            throw new ApiException("Missing the required parameter 'updateTicketRequest' when calling updateTicket(Async)");
        }

        return updateTicketCall(ticketId, updateTicketRequest, _callback);

    }

    /**
     * Met à jour un ticket
     * Modifie un ticket existant. Les admins/développeurs peuvent modifier tous les tickets. Les utilisateurs ne peuvent modifier que leurs propres tickets. 
     * @param ticketId Identifiant unique du ticket (required)
     * @param updateTicketRequest  (required)
     * @return TicketDTO
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Ticket modifié avec succès </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Requête invalide (validation échouée) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ressource non trouvée </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Accès refusé (permissions insuffisantes) </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erreur interne du serveur </td><td>  -  </td></tr>
     </table>
     */
    public TicketDTO updateTicket(Integer ticketId, UpdateTicketRequest updateTicketRequest) throws ApiException {
        ApiResponse<TicketDTO> localVarResp = updateTicketWithHttpInfo(ticketId, updateTicketRequest);
        return localVarResp.getData();
    }

    /**
     * Met à jour un ticket
     * Modifie un ticket existant. Les admins/développeurs peuvent modifier tous les tickets. Les utilisateurs ne peuvent modifier que leurs propres tickets. 
     * @param ticketId Identifiant unique du ticket (required)
     * @param updateTicketRequest  (required)
     * @return ApiResponse&lt;TicketDTO&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Ticket modifié avec succès </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Requête invalide (validation échouée) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ressource non trouvée </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Accès refusé (permissions insuffisantes) </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erreur interne du serveur </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<TicketDTO> updateTicketWithHttpInfo(Integer ticketId, UpdateTicketRequest updateTicketRequest) throws ApiException {
        okhttp3.Call localVarCall = updateTicketValidateBeforeCall(ticketId, updateTicketRequest, null);
        Type localVarReturnType = new TypeToken<TicketDTO>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Met à jour un ticket (asynchronously)
     * Modifie un ticket existant. Les admins/développeurs peuvent modifier tous les tickets. Les utilisateurs ne peuvent modifier que leurs propres tickets. 
     * @param ticketId Identifiant unique du ticket (required)
     * @param updateTicketRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Ticket modifié avec succès </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Requête invalide (validation échouée) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ressource non trouvée </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Accès refusé (permissions insuffisantes) </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erreur interne du serveur </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateTicketAsync(Integer ticketId, UpdateTicketRequest updateTicketRequest, final ApiCallback<TicketDTO> _callback) throws ApiException {

        okhttp3.Call localVarCall = updateTicketValidateBeforeCall(ticketId, updateTicketRequest, _callback);
        Type localVarReturnType = new TypeToken<TicketDTO>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for updateTicketDescription
     * @param ticketId Identifiant unique du ticket (required)
     * @param description  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Description mise à jour avec succès </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ressource non trouvée </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Requête invalide (validation échouée) </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erreur interne du serveur </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateTicketDescriptionCall(Integer ticketId, Description description, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = description;

        // create path and map variables
        String localVarPath = "/tickets/{ticketId}/description"
            .replace("{" + "ticketId" + "}", localVarApiClient.escapeString(ticketId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call updateTicketDescriptionValidateBeforeCall(Integer ticketId, Description description, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'ticketId' is set
        if (ticketId == null) {
            throw new ApiException("Missing the required parameter 'ticketId' when calling updateTicketDescription(Async)");
        }

        // verify the required parameter 'description' is set
        if (description == null) {
            throw new ApiException("Missing the required parameter 'description' when calling updateTicketDescription(Async)");
        }

        return updateTicketDescriptionCall(ticketId, description, _callback);

    }

    /**
     * Met à jour la description d&#39;un ticket
     * Modifie la description d&#39;un ticket existant
     * @param ticketId Identifiant unique du ticket (required)
     * @param description  (required)
     * @return TicketDTO
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Description mise à jour avec succès </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ressource non trouvée </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Requête invalide (validation échouée) </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erreur interne du serveur </td><td>  -  </td></tr>
     </table>
     */
    public TicketDTO updateTicketDescription(Integer ticketId, Description description) throws ApiException {
        ApiResponse<TicketDTO> localVarResp = updateTicketDescriptionWithHttpInfo(ticketId, description);
        return localVarResp.getData();
    }

    /**
     * Met à jour la description d&#39;un ticket
     * Modifie la description d&#39;un ticket existant
     * @param ticketId Identifiant unique du ticket (required)
     * @param description  (required)
     * @return ApiResponse&lt;TicketDTO&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Description mise à jour avec succès </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ressource non trouvée </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Requête invalide (validation échouée) </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erreur interne du serveur </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<TicketDTO> updateTicketDescriptionWithHttpInfo(Integer ticketId, Description description) throws ApiException {
        okhttp3.Call localVarCall = updateTicketDescriptionValidateBeforeCall(ticketId, description, null);
        Type localVarReturnType = new TypeToken<TicketDTO>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Met à jour la description d&#39;un ticket (asynchronously)
     * Modifie la description d&#39;un ticket existant
     * @param ticketId Identifiant unique du ticket (required)
     * @param description  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Description mise à jour avec succès </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ressource non trouvée </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Requête invalide (validation échouée) </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erreur interne du serveur </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateTicketDescriptionAsync(Integer ticketId, Description description, final ApiCallback<TicketDTO> _callback) throws ApiException {

        okhttp3.Call localVarCall = updateTicketDescriptionValidateBeforeCall(ticketId, description, _callback);
        Type localVarReturnType = new TypeToken<TicketDTO>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for updateTicketPriority
     * @param ticketId Identifiant unique du ticket (required)
     * @param updateTicketPriorityRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Priorité mise à jour avec succès </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Requête invalide (validation échouée) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ressource non trouvée </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Accès refusé (permissions insuffisantes) </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erreur interne du serveur </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateTicketPriorityCall(Integer ticketId, UpdateTicketPriorityRequest updateTicketPriorityRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = updateTicketPriorityRequest;

        // create path and map variables
        String localVarPath = "/tickets/{ticketId}/priority"
            .replace("{" + "ticketId" + "}", localVarApiClient.escapeString(ticketId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call updateTicketPriorityValidateBeforeCall(Integer ticketId, UpdateTicketPriorityRequest updateTicketPriorityRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'ticketId' is set
        if (ticketId == null) {
            throw new ApiException("Missing the required parameter 'ticketId' when calling updateTicketPriority(Async)");
        }

        // verify the required parameter 'updateTicketPriorityRequest' is set
        if (updateTicketPriorityRequest == null) {
            throw new ApiException("Missing the required parameter 'updateTicketPriorityRequest' when calling updateTicketPriority(Async)");
        }

        return updateTicketPriorityCall(ticketId, updateTicketPriorityRequest, _callback);

    }

    /**
     * Modifie la priorité d&#39;un ticket
     * Met à jour la priorité d&#39;un ticket spécifique
     * @param ticketId Identifiant unique du ticket (required)
     * @param updateTicketPriorityRequest  (required)
     * @return TicketDTO
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Priorité mise à jour avec succès </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Requête invalide (validation échouée) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ressource non trouvée </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Accès refusé (permissions insuffisantes) </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erreur interne du serveur </td><td>  -  </td></tr>
     </table>
     */
    public TicketDTO updateTicketPriority(Integer ticketId, UpdateTicketPriorityRequest updateTicketPriorityRequest) throws ApiException {
        ApiResponse<TicketDTO> localVarResp = updateTicketPriorityWithHttpInfo(ticketId, updateTicketPriorityRequest);
        return localVarResp.getData();
    }

    /**
     * Modifie la priorité d&#39;un ticket
     * Met à jour la priorité d&#39;un ticket spécifique
     * @param ticketId Identifiant unique du ticket (required)
     * @param updateTicketPriorityRequest  (required)
     * @return ApiResponse&lt;TicketDTO&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Priorité mise à jour avec succès </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Requête invalide (validation échouée) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ressource non trouvée </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Accès refusé (permissions insuffisantes) </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erreur interne du serveur </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<TicketDTO> updateTicketPriorityWithHttpInfo(Integer ticketId, UpdateTicketPriorityRequest updateTicketPriorityRequest) throws ApiException {
        okhttp3.Call localVarCall = updateTicketPriorityValidateBeforeCall(ticketId, updateTicketPriorityRequest, null);
        Type localVarReturnType = new TypeToken<TicketDTO>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Modifie la priorité d&#39;un ticket (asynchronously)
     * Met à jour la priorité d&#39;un ticket spécifique
     * @param ticketId Identifiant unique du ticket (required)
     * @param updateTicketPriorityRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Priorité mise à jour avec succès </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Requête invalide (validation échouée) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ressource non trouvée </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Accès refusé (permissions insuffisantes) </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erreur interne du serveur </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateTicketPriorityAsync(Integer ticketId, UpdateTicketPriorityRequest updateTicketPriorityRequest, final ApiCallback<TicketDTO> _callback) throws ApiException {

        okhttp3.Call localVarCall = updateTicketPriorityValidateBeforeCall(ticketId, updateTicketPriorityRequest, _callback);
        Type localVarReturnType = new TypeToken<TicketDTO>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
