/*
 * Système de Gestion de Tickets (SBIR), API REST
 * API REST pour le système de gestion de tickets développé en Java pour le cours 6GEI311, Architecture Logicielle  Auteurs: Il'aina Ratefinanahary et Samuel Brassard, UQAC Automne 2025 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: iratefinan@etu.uqac.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiCallback;
import org.openapitools.client.ApiClient;
import org.openapitools.client.ApiException;
import org.openapitools.client.ApiResponse;
import org.openapitools.client.Configuration;
import org.openapitools.client.Pair;

import com.google.gson.reflect.TypeToken;

import org.openapitools.client.model.UserCreate;
import org.openapitools.client.model.UserDTO;
import org.openapitools.client.model.UserUpdate;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class UsersApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public UsersApi() {
        this(Configuration.getDefaultApiClient());
    }

    public UsersApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for createUser
     * @param userCreate Données de l&#39;utilisateur à créer (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Utilisateur créé avec succès </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Requête invalide (validation échouée) </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erreur interne du serveur </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createUserCall(UserCreate userCreate, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = userCreate;

        // create path and map variables
        String localVarPath = "/users";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call createUserValidateBeforeCall(UserCreate userCreate, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'userCreate' is set
        if (userCreate == null) {
            throw new ApiException("Missing the required parameter 'userCreate' when calling createUser(Async)");
        }

        return createUserCall(userCreate, _callback);

    }

    /**
     * Crée un nouvel utilisateur
     * Crée un nouvel utilisateur dans le système
     * @param userCreate Données de l&#39;utilisateur à créer (required)
     * @return UserDTO
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Utilisateur créé avec succès </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Requête invalide (validation échouée) </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erreur interne du serveur </td><td>  -  </td></tr>
     </table>
     */
    public UserDTO createUser(UserCreate userCreate) throws ApiException {
        ApiResponse<UserDTO> localVarResp = createUserWithHttpInfo(userCreate);
        return localVarResp.getData();
    }

    /**
     * Crée un nouvel utilisateur
     * Crée un nouvel utilisateur dans le système
     * @param userCreate Données de l&#39;utilisateur à créer (required)
     * @return ApiResponse&lt;UserDTO&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Utilisateur créé avec succès </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Requête invalide (validation échouée) </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erreur interne du serveur </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<UserDTO> createUserWithHttpInfo(UserCreate userCreate) throws ApiException {
        okhttp3.Call localVarCall = createUserValidateBeforeCall(userCreate, null);
        Type localVarReturnType = new TypeToken<UserDTO>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Crée un nouvel utilisateur (asynchronously)
     * Crée un nouvel utilisateur dans le système
     * @param userCreate Données de l&#39;utilisateur à créer (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Utilisateur créé avec succès </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Requête invalide (validation échouée) </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erreur interne du serveur </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createUserAsync(UserCreate userCreate, final ApiCallback<UserDTO> _callback) throws ApiException {

        okhttp3.Call localVarCall = createUserValidateBeforeCall(userCreate, _callback);
        Type localVarReturnType = new TypeToken<UserDTO>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for deleteUser
     * @param userId Identifiant unique de l&#39;utilisateur (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Utilisateur supprimé avec succès </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ressource non trouvée </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Accès refusé (permissions insuffisantes) </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erreur interne du serveur </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteUserCall(Integer userId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/users/{userId}"
            .replace("{" + "userId" + "}", localVarApiClient.escapeString(userId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call deleteUserValidateBeforeCall(Integer userId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'userId' is set
        if (userId == null) {
            throw new ApiException("Missing the required parameter 'userId' when calling deleteUser(Async)");
        }

        return deleteUserCall(userId, _callback);

    }

    /**
     * Supprime un utilisateur
     * Supprime un utilisateur du système
     * @param userId Identifiant unique de l&#39;utilisateur (required)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Utilisateur supprimé avec succès </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ressource non trouvée </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Accès refusé (permissions insuffisantes) </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erreur interne du serveur </td><td>  -  </td></tr>
     </table>
     */
    public void deleteUser(Integer userId) throws ApiException {
        deleteUserWithHttpInfo(userId);
    }

    /**
     * Supprime un utilisateur
     * Supprime un utilisateur du système
     * @param userId Identifiant unique de l&#39;utilisateur (required)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Utilisateur supprimé avec succès </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ressource non trouvée </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Accès refusé (permissions insuffisantes) </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erreur interne du serveur </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> deleteUserWithHttpInfo(Integer userId) throws ApiException {
        okhttp3.Call localVarCall = deleteUserValidateBeforeCall(userId, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * Supprime un utilisateur (asynchronously)
     * Supprime un utilisateur du système
     * @param userId Identifiant unique de l&#39;utilisateur (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Utilisateur supprimé avec succès </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ressource non trouvée </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Accès refusé (permissions insuffisantes) </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erreur interne du serveur </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteUserAsync(Integer userId, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = deleteUserValidateBeforeCall(userId, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
    /**
     * Build call for getAllUsers
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Liste des utilisateurs récupérée avec succès </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erreur interne du serveur </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getAllUsersCall(final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/users";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getAllUsersValidateBeforeCall(final ApiCallback _callback) throws ApiException {
        return getAllUsersCall(_callback);

    }

    /**
     * Liste tous les utilisateurs
     * Retourne la liste complète des utilisateurs du système
     * @return List&lt;UserDTO&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Liste des utilisateurs récupérée avec succès </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erreur interne du serveur </td><td>  -  </td></tr>
     </table>
     */
    public List<UserDTO> getAllUsers() throws ApiException {
        ApiResponse<List<UserDTO>> localVarResp = getAllUsersWithHttpInfo();
        return localVarResp.getData();
    }

    /**
     * Liste tous les utilisateurs
     * Retourne la liste complète des utilisateurs du système
     * @return ApiResponse&lt;List&lt;UserDTO&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Liste des utilisateurs récupérée avec succès </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erreur interne du serveur </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<List<UserDTO>> getAllUsersWithHttpInfo() throws ApiException {
        okhttp3.Call localVarCall = getAllUsersValidateBeforeCall(null);
        Type localVarReturnType = new TypeToken<List<UserDTO>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Liste tous les utilisateurs (asynchronously)
     * Retourne la liste complète des utilisateurs du système
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Liste des utilisateurs récupérée avec succès </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erreur interne du serveur </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getAllUsersAsync(final ApiCallback<List<UserDTO>> _callback) throws ApiException {

        okhttp3.Call localVarCall = getAllUsersValidateBeforeCall(_callback);
        Type localVarReturnType = new TypeToken<List<UserDTO>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getUserById
     * @param userId Identifiant unique de l&#39;utilisateur (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Utilisateur trouvé </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ressource non trouvée </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erreur interne du serveur </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getUserByIdCall(Integer userId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/users/{userId}"
            .replace("{" + "userId" + "}", localVarApiClient.escapeString(userId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getUserByIdValidateBeforeCall(Integer userId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'userId' is set
        if (userId == null) {
            throw new ApiException("Missing the required parameter 'userId' when calling getUserById(Async)");
        }

        return getUserByIdCall(userId, _callback);

    }

    /**
     * Récupère un utilisateur spécifique
     * Retourne les détails d&#39;un utilisateur par son ID
     * @param userId Identifiant unique de l&#39;utilisateur (required)
     * @return UserDTO
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Utilisateur trouvé </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ressource non trouvée </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erreur interne du serveur </td><td>  -  </td></tr>
     </table>
     */
    public UserDTO getUserById(Integer userId) throws ApiException {
        ApiResponse<UserDTO> localVarResp = getUserByIdWithHttpInfo(userId);
        return localVarResp.getData();
    }

    /**
     * Récupère un utilisateur spécifique
     * Retourne les détails d&#39;un utilisateur par son ID
     * @param userId Identifiant unique de l&#39;utilisateur (required)
     * @return ApiResponse&lt;UserDTO&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Utilisateur trouvé </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ressource non trouvée </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erreur interne du serveur </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<UserDTO> getUserByIdWithHttpInfo(Integer userId) throws ApiException {
        okhttp3.Call localVarCall = getUserByIdValidateBeforeCall(userId, null);
        Type localVarReturnType = new TypeToken<UserDTO>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Récupère un utilisateur spécifique (asynchronously)
     * Retourne les détails d&#39;un utilisateur par son ID
     * @param userId Identifiant unique de l&#39;utilisateur (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Utilisateur trouvé </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ressource non trouvée </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erreur interne du serveur </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getUserByIdAsync(Integer userId, final ApiCallback<UserDTO> _callback) throws ApiException {

        okhttp3.Call localVarCall = getUserByIdValidateBeforeCall(userId, _callback);
        Type localVarReturnType = new TypeToken<UserDTO>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for updateUser
     * @param userId Identifiant unique de l&#39;utilisateur (required)
     * @param userUpdate  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Utilisateur mis à jour avec succès </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Requête invalide (validation échouée) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ressource non trouvée </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erreur interne du serveur </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateUserCall(Integer userId, UserUpdate userUpdate, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = userUpdate;

        // create path and map variables
        String localVarPath = "/users/{userId}"
            .replace("{" + "userId" + "}", localVarApiClient.escapeString(userId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call updateUserValidateBeforeCall(Integer userId, UserUpdate userUpdate, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'userId' is set
        if (userId == null) {
            throw new ApiException("Missing the required parameter 'userId' when calling updateUser(Async)");
        }

        // verify the required parameter 'userUpdate' is set
        if (userUpdate == null) {
            throw new ApiException("Missing the required parameter 'userUpdate' when calling updateUser(Async)");
        }

        return updateUserCall(userId, userUpdate, _callback);

    }

    /**
     * Met à jour un utilisateur
     * Met à jour les informations d&#39;un utilisateur existant
     * @param userId Identifiant unique de l&#39;utilisateur (required)
     * @param userUpdate  (required)
     * @return UserDTO
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Utilisateur mis à jour avec succès </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Requête invalide (validation échouée) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ressource non trouvée </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erreur interne du serveur </td><td>  -  </td></tr>
     </table>
     */
    public UserDTO updateUser(Integer userId, UserUpdate userUpdate) throws ApiException {
        ApiResponse<UserDTO> localVarResp = updateUserWithHttpInfo(userId, userUpdate);
        return localVarResp.getData();
    }

    /**
     * Met à jour un utilisateur
     * Met à jour les informations d&#39;un utilisateur existant
     * @param userId Identifiant unique de l&#39;utilisateur (required)
     * @param userUpdate  (required)
     * @return ApiResponse&lt;UserDTO&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Utilisateur mis à jour avec succès </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Requête invalide (validation échouée) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ressource non trouvée </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erreur interne du serveur </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<UserDTO> updateUserWithHttpInfo(Integer userId, UserUpdate userUpdate) throws ApiException {
        okhttp3.Call localVarCall = updateUserValidateBeforeCall(userId, userUpdate, null);
        Type localVarReturnType = new TypeToken<UserDTO>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Met à jour un utilisateur (asynchronously)
     * Met à jour les informations d&#39;un utilisateur existant
     * @param userId Identifiant unique de l&#39;utilisateur (required)
     * @param userUpdate  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Utilisateur mis à jour avec succès </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Requête invalide (validation échouée) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ressource non trouvée </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Erreur interne du serveur </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateUserAsync(Integer userId, UserUpdate userUpdate, final ApiCallback<UserDTO> _callback) throws ApiException {

        okhttp3.Call localVarCall = updateUserValidateBeforeCall(userId, userUpdate, _callback);
        Type localVarReturnType = new TypeToken<UserDTO>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
