/*
 * Système de Gestion de Tickets (SBIR), API REST
 * API REST pour le système de gestion de tickets développé en Java pour le cours 6GEI311, Architecture Logicielle  Auteurs: Il'aina Ratefinanahary et Samuel Brassard, UQAC Automne 2025 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: iratefinan@etu.uqac.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-18T07:17:48.683432600-05:00[America/Toronto]", comments = "Generator version: 7.10.0")
public class Configuration {
    public static final String VERSION = "4.0.0";

    private static ApiClient defaultApiClient = new ApiClient();

    /**
     * Get the default API client, which would be used when creating API
     * instances without providing an API client.
     *
     * @return Default API client
     */
    public static ApiClient getDefaultApiClient() {
        return defaultApiClient;
    }

    /**
     * Set the default API client, which would be used when creating API
     * instances without providing an API client.
     *
     * @param apiClient API client
     */
    public static void setDefaultApiClient(ApiClient apiClient) {
        defaultApiClient = apiClient;
    }
}
